import { ErrorCodes } from "./enums";
import { TransactionData } from "./types";

export const DEFAULT_LANG = "en";

const Translations = {
  en: {
    xor_label: "XOR",
    atbash_label: "Atbash",
    caesar_label: "Caesar",
    vigenere_label: "Vigenère",
    title: "Encryption Methods",
    choose_method: "Choose an encryption method",
    caesar: "Caesar Cipher",
    atbash: "Atbash Cipher",
    vigenere: "Vigenère Cipher",
    xor: "XOR Cipher",
    method_label: "Encryption Method",
    choose_method_option: "Choose a method",
    continue: "Continue",
    alert_choose: "Please choose an encryption method.",
    title_round: "Cipher",
    cipher: "Cipher",
    input_text: "Enter text:",
    shift_key: "Shift / Key:",
    decrypt: "Decrypt",
    open_file: "Open file",
    save_result: "Save result",
    history: "History",
    run: "Run",
    result: "Result:",
    history_title: "Encryption history",
    param_shift: "Shift:",
    param_key: "Key:",
    param_param: "Parameter:",
    alert_no_text: "No text to save.",
    prompt_filename: "Enter filename to save:",
    log_empty: "Log is empty.",
    cancel: "Cancel",
    save: "Save",
    request_error: "Error during request",
    [ErrorCodes.ControllerBug]: "Controller error",
    [ErrorCodes.ControllerMethodBug]: "Controller error: method",
    [ErrorCodes.EmptyLog]: "Empty log",
    [ErrorCodes.FileNotSelected]: "File not selected",
    [ErrorCodes.FileSaveBug]: "File save error",
    [ErrorCodes.KeyJustHaveLetters]: "Key must contain only letters",
    [ErrorCodes.LogNotCreated]: "Log not created",
    [ErrorCodes.OpenFileBug]: "File open error",
    [ErrorCodes.OpenLogBug]: "Log open error",
    [ErrorCodes.ParamNotInteger]: "Parameter must be a number",
    [ErrorCodes.ParamNotString]: "Parameter must be a string",
    [ErrorCodes.UnknownMethod]: "Unknown method",
  },
  ru: {
    xor_label: "XOR",
    atbash_label: "Атбаш",
    caesar_label: "Цезарь",
    vigenere_label: "Виженер",
    title: "Методы шифрования",
    choose_method: "Выберите метод шифрования",
    caesar: "Шифр Цезаря",
    atbash: "Шифр Атбаш",
    vigenere: "Шифр Виженера",
    xor: "Шифр XOR",
    method_label: "Метод шифрования",
    choose_method_option: "Выберите метод",
    continue: "Продолжить",
    alert_choose: "Пожалуйста, выберите метод шифрования.",
    title_round: "Шифр",
    cipher: "Шифр",
    input_text: "Введите текст:",
    shift_key: "Сдвиг / Ключ:",
    decrypt: "Расшифровать",
    open_file: "Открыть файл",
    save_result: "Сохранить результат",
    history: "История",
    run: "Запустить",
    result: "Результат:",
    history_title: "История шифрования",
    param_shift: "Сдвиг:",
    param_key: "Ключ:",
    param_param: "Параметр:",
    alert_no_text: "Нет текста для сохранения.",
    prompt_filename: "Введите имя файла для сохранения:",
    log_empty: "Журнал пуст.",
    cancel: "Отмена",
    save: "Сохранить",
    request_error: "Ошибка при запросе",
    [ErrorCodes.ControllerBug]: "Ошибка контроллера",
    [ErrorCodes.ControllerMethodBug]: "Ошибка контроллера: метод",
    [ErrorCodes.EmptyLog]: "Пустой журнал",
    [ErrorCodes.FileNotSelected]: "Файл не выбран",
    [ErrorCodes.FileSaveBug]: "Ошибка сохранения файла",
    [ErrorCodes.KeyJustHaveLetters]: "Ключ должен содержать только буквы",
    [ErrorCodes.LogNotCreated]: "Журнал не создан",
    [ErrorCodes.OpenFileBug]: "Ошибка открытия файла",
    [ErrorCodes.OpenLogBug]: "Ошибка открытия журнала",
    [ErrorCodes.ParamNotInteger]: "Параметр должен быть числом",
    [ErrorCodes.ParamNotString]: "Параметр должен быть строкой",
    [ErrorCodes.UnknownMethod]: "Неизвестный метод",
  },
  ua: {
    xor_label: "XOR",
    atbash_label: "Атбаш",
    caesar_label: "Цезар",
    vigenere_label: "Віженер",
    title: "Методи шифрування",
    choose_method: "Оберіть метод шифрування",
    caesar: "Шифр Цезаря",
    atbash: "Шифр Атбаш",
    vigenere: "Шифр Віженера",
    xor: "Шифр XOR",
    method_label: "Метод шифрування",
    choose_method_option: "Оберіть метод",
    continue: "Продовжити",
    alert_choose: "Будь ласка, оберіть метод шифрування.",
    title_round: "Шифр",
    cipher: "Шифр",
    input_text: "Введіть текст:",
    shift_key: "Зсув / Ключ:",
    decrypt: "Розшифрувати",
    open_file: "Відкрити файл",
    save_result: "Зберегти результат",
    history: "Історія",
    run: "Запустити",
    result: "Результат:",
    history_title: "Історія шифрування",
    param_shift: "Зсув:",
    param_key: "Ключ:",
    param_param: "Параметр:",
    alert_no_text: "Немає тексту для збереження.",
    prompt_filename: "Введіть ім'я файлу для збереження:",
    log_empty: "Журнал порожній.",
    cancel: "Скасувати",
    save: "Зберегти",
    request_error: "Помилка під час запиту",
    [ErrorCodes.ControllerBug]: "Помилка контролера",
    [ErrorCodes.ControllerMethodBug]: "Помилка контролера: метод",
    [ErrorCodes.EmptyLog]: "Порожній журнал",
    [ErrorCodes.FileNotSelected]: "Файл не вибрано",
    [ErrorCodes.FileSaveBug]: "Помилка збереження файлу",
    [ErrorCodes.KeyJustHaveLetters]: "Ключ повинен містити лише літери",
    [ErrorCodes.LogNotCreated]: "Журнал не створено",
    [ErrorCodes.OpenFileBug]: "Помилка відкриття файлу",
    [ErrorCodes.OpenLogBug]: "Помилка відкриття журналу",
    [ErrorCodes.ParamNotInteger]: "Параметр повинен бути числом",
    [ErrorCodes.ParamNotString]: "Параметр повинен бути рядком",
    [ErrorCodes.UnknownMethod]: "Невідомий метод",
  },
};

export default function getTranslation(
  lang: string = DEFAULT_LANG
): TransactionData {
  return Translations[lang as keyof typeof Translations];
}
